Final? update of Gibbs notebook
CUQI-DTU/CUQIpy-demos pull request #51
Opened 2022-09-23 22:21 UTC by nabriis

Closes #45

2022-09-24 19:17 UTC, jakobsj requested changes
Nice adjustments and additional explanations. I added some fairly minor in line suggestions. Also, might it make sense to display some posterior samples at the end of section 3?

2022-09-24 19:17 UTC, jakobsj commented on training/Exercise06_Gibbs.ipynb
> +    "Try evaluting the un-normalized log probability density (logd) of the posterior distribution $p(\\mathbf{x}, d, s \\mid \\mathbf{y}_\\mathrm{data})$ at some points $\\mathbf{x}^*\\in \\R^n$, $d^
```suggestion
    "Try evaluting the un-normalized log probability density (logd) of the posterior distribution $p(\\mathbf{x}, d, s \\mid \\mathbf{y}_\\mathrm{data})$ at some points $\\mathbf{x}^*\\in \\mathbb{R}^n$, $d^*\\in \\mathbb{R}_+$ and $s^*\\in \\mathbb{R}_+$.\n",
```

2022-09-24 19:17 UTC, jakobsj commented on training/Exercise06_Gibbs.ipynb
>      "the Gamma distribution are conjugate priors for the precision of\n",
Something wrong about the sentence "Gamma distribution are conjugate priors for the precision of the Gaussian distribution". Are should be is I guess, and is it a conjugate PRIOR or conjugate DISTRIBUTION? It is not conjugate to the PRECISION of the Gaussian distribution, is it, rather to the Gaussian distribution?

2022-09-24 19:17 UTC, jakobsj commented on training/Exercise06_Gibbs.ipynb
>      "\\mathbf{x} \\sim \\text{Laplace\\_diff}(\\mathbf{0}, d^{-1}),\n",
```suggestion
    "\\mathbf{x} \\sim \\text{Laplace\_diff}(\\mathbf{0}, d^{-1}),\n",
```
(I think - it currently shows an additional backslash when viewing in jupyter lab)

2022-09-25 12:59 UTC, nabriis commented on training/Exercise06_Gibbs.ipynb
> +    "The above example was a simple example to illustrate the basic idea of Gibbs sampling. However, often for these simple examples there exist more efficient sampling methods. In the following we i
Added manually because missing "to"

2022-09-25 13:06 UTC, nabriis commented on training/Exercise06_Gibbs.ipynb
> +    "To see that the Gamma hyperprior is weakly informative, we can visualize the pdf of the Gamma distribution"
Done

2022-09-25 13:09 UTC, nabriis commented on training/Exercise06_Gibbs.ipynb
>      "the Gamma distribution are conjugate priors for the precision of\n",
I tried to update it!

2022-09-25 13:11 UTC, nabriis commented on training/Exercise06_Gibbs.ipynb
>      "\n",
Done

2022-09-25 14:33 UTC, jakobsj approved these changes
Only took brief look, but seems good!

2022-09-25 15:23 UTC, merged